# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  #- 5.2
  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  #- 5.4

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - wget http://wordpress.org/latest.tar.gz
  - tar -xzf latest.tar.gz
  - cd wordpress/wp-content/plugins
  - mysql -e "create database IF NOT EXISTS test;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit
